name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps: 
      - name: Hämta kod från GitHub
        uses: actions/checkout@v4

      - name: Sätt upp Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Installera dependencies
        run: npm install

  test: 
     name: Test
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Hämta kod från GitHub
         uses: actions/checkout@v4
       
       - name: Sätt upp Node.js
         uses: actions/setup-node@v4
         with: 
          node-version: '20'
          cache: 'npm'
 
       - name: installera dependencies
         run: npm ci

       - name: run tests
         run: npm test
  
  sast: 
    name: Statistisk kodanalys
    runs-on: ubuntu-latest
    needs: build

    steps:
       - name: Hämta kod från GitHub
         uses: actions/checkout@v4
       
       - name: Sätt upp Node.js
         uses: actions/setup-node@v4
         with: 
          node-version: '20'
          cache: 'npm'
 
       - name: installera dependencies
         run: npm ci

       - name: installera ES-lint Säkerhetsplugin
         run: npm install --save-dev eslint eslint-plugin-security

       - name: run Sast test
         run: npx eslint src/

  sca:
    name: SCA beroende scan
    runs-on: ubuntu-latest
    needs: build

    steps:
       - name: Hämta kod från GitHub
         uses: actions/checkout@v4

       - name: OWASP Dependency Check
         uses: dependency-check/Dependency-Check_Action@main
         with:
          project: 'test'
          path: '.'
          format: 'HTML'
          args: --failOnCVSS 8
       
       - name: Upload Report
         uses: actions/upload-artifact@v4
         if: always()
         with:
          name: dependency-check-report
          path: reports/

