name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps: 
      - name: Hämta kod från GitHub
        uses: actions/checkout@v4

      - name: Sätt upp Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Installera dependencies
        run: npm install

  test: 
     name: Test
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Hämta kod från GitHub
         uses: actions/checkout@v4
       
       - name: Sätt upp Node.js
         uses: actions/setup-node@v4
         with: 
          node-version: '20'
          cache: 'npm'
 
       - name: installera dependencies
         run: npm ci

       - name: run tests
         run: npm test
  
  sast: 
    name: Statistisk kodanalys
    runs-on: ubuntu-latest
    needs: build

    steps:
       - name: Hämta kod från GitHub
         uses: actions/checkout@v4
       
       - name: Sätt upp Node.js
         uses: actions/setup-node@v4
         with: 
          node-version: '20'
          cache: 'npm'
 
       - name: installera dependencies
         run: npm ci

       - name: installera ES-lint Säkerhetsplugin
         run: npm install --save-dev eslint eslint-plugin-security

       - name: run Sast test
         run: npx eslint src/

  sca:
    name: SCA beroende scan
    runs-on: ubuntu-latest
    needs: build

    steps:
       - name: Hämta kod från GitHub
         uses: actions/checkout@v4

       - name: OWASP Dependency Check
         uses: dependency-check/Dependency-Check_Action@main
         with:
          project: 'test'
          path: '.'
          format: 'HTML'
          args: --failOnCVSS 9 --exclude "**/node_modules/**"
       
       - name: Upload Report
         uses: actions/upload-artifact@v4
         if: always()
         with:
          name: dependency-check-report
          path: reports/

  container-scanning:
    name: container scanner
    runs-on: ubuntu-latest
    needs: [build, test, sast, sca ]

    steps:
      - name: Hämta kod från GitHub
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t lektion-8-app:latest .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'lektion-8-app:latest'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          skip-dirs: '/usr/local/lib/node_modules/npm'
 
  deploy: 
    name: deploy
    runs-on: ubuntu-latest
    needs: [ build, test, sast, sca, container-scanning ]
    if: github.event_name == 'push'

    steps:
      - name: Hämta kod från GitHub
        uses: actions/checkout@v4

      - name: Simulerad deploy till testmiljö
        run: |
          echo "Alla säkerhetstester godkänt"
          echo "Ready for deploy"
          echo "Deploy klar"